### ISSUE TITLE
[Discussion] Resolver simplification

### ISSUE THREAD

**Issue by ecwyne** [gramps-graphql/gramps#51]
@jlengstorf @corycook
I wanted to see if anyone else thought this would be helpful.

```javascript
// Optionally turn this
const resolvers = {
  Query: {
    getLatestComic: (_, __, context) => context.getLatestComic(),
    getComicById: (_, { id }, context) => context.getComicById(id),
  },
  XKCD_Comic: {
    link: data => data.link || `https://xkcd.com/${data.num}/`,
  },
};

// Into this
const resolvers = {
  Query: {
    getLatestComic: ctx => ctx.getLatestComic(),
    getComicById: (ctx, args) => ctx.getComicById(args.id),
  },
  XKCD_Comic: {
    link: p => p.link || `https://xkcd.com/${p.num}/`,
  }
};
```

To do so, all you need to do is wrap each resolver function with this.
```javascript
import reflector from 'js-function-reflector'; // https://www.npmjs.com/package/js-function-reflector

const reflect = fn => {
	const {args: arr} = reflector(fn);
	return (parent, args, context, info) => {
		const obj = {
			p: parent,
			parent,
			r: parent,
			root: parent,
			a: args,
			args,
			c: context,
			ctx: context,
			context,
			i: info,
			info,
		};
		return fn.apply(null, arr.map((e, i) => obj[e] || arguments[i]))
	}
};
```

This checks the argument names of the provided function `fn` and replaces:
`p || parent || r || root` with the 1st argument to the resolver function
`a || args` with the 2nd argument
`c || ctx || context` with the 3rd argument
`i || info` with the 4th argument
defaults to the nth argument

Mainly, my question is whether or not everyone else is tired of writing resolver functions with all 4 arguments and only using one or two of them

**Comment by ecwyne** [comment]
The distinct downside for me is the inability to destructure arguments

```javascript
const resolvers = {
  Query: {
    getComicById: (_, { id }, { getComicById }) => getComicById(id)
  }
};
```

But, again, there's nothing stopping you from using resolvers like normal because they default to the nth argument and I'll think if there's any other way to figure out destructuring

**Comment by felixfbecker** [comment]
Magic reflection by parsing `function.toString()`? Please don't. This will break in a thousand edge cases. It may break during transpilation / minification / obfuscation. It will be impossible to type in TypeScript/Flow. It will be impossible to get help from IDEs.

If this is really a problem, the resolvers should receive a single object that an be destructured as pleased.

**Comment by jlengstorf** [comment]
I do find it a little annoying to have a ton of `fieldName: (_, args, context) => context.thing()` calls, but I agree with @felixfbecker that implementing this at the GrAMPS level will end up biting us in the ass later on in many unpredictable ways.

We could write up a proposal to simplify the API upstream, however. If I had my druthers, I'd want the args to be turned into an object we can destructure.

So instead of:
```js
(rootValue, args, context, info) => //...
```
I'd love:
```js
({ context }) => //...
// or
({ context, args: { id } }) => //...
```

That would give developers more control. But that's just my preference, and not something I think we should impose on the people using GrAMPS.

If anyone else wants to weigh in, I'm happy to hear differing opinions, but I think this is something that shouldn't be a GrAMPS decision. (That being said, you could always write a utility function for _your_ data sources; I don't know that I'd personally recommend that, but it's certainly possible.)

Otherwise, I'm recommending we close this as out-of-scope.
